#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_ICON1                               101
#define IDR_ACCELERATOR1                        102
#define IDR_MENU_MAIN                           104
#define IDR_MENU_LEVEL                          105
#define IDD_DIALOG_LIST_SELECT                  106
#define IDR_MENU_TOOLBAR                        109
#define IDB_BITMAP_TOOLS                        115
#define IDD_DIALOG_BROWSER                      119
#define IDD_DIALOG_BROWSER_OBJ                  120
#define IDD_DIALOG_SAVE_AS                      122
#define IDD_DIALOG_EDITOR_OBJ                   123
#define IDB_BITMAP_COLOUR_PICK                  125
#define IDC_BROWSER_TAB                         1001
#define IDC_COMBO_TYPE                          1001
#define IDC_SAVE_AS_EDIT                        1001
#define IDC_LIST_SELECT_EDIT                    40000
#define IDC_OBJ_NAME                            40000
#define IDM_MAP_NEW                             40000
#define IDC_LIST_SELECT_LIST                    40001
#define IDC_OBJ_PIC                             40001
#define IDM_MAP_OPEN                            40001
#define IDC_EDIT_L_INT                          40002
#define IDM_MAP_SAVE                            40002
#define IDM_MAP_SAVE_AS                         40003
#define IDC_L_COLOUR                            40004
#define IDM_QUIT_MAPPER                         40004
#define IDM_VIEW_ROOVES                         40005
#define IDM_VIEW_HEXES                          40006
#define IDM_VIEW_BLOCKERS                       40007
#define IDM_VIEW_ITEMS                          40008
#define IDM_VIEW_CRITTERS                       40009
#define IDM_VIEW_SCENERY                        40010
#define IDM_VIEW_WALLS                          40011
#define IDM_VIEW_TILES                          40012
#define IDM_VIEW_MISC                           40013
#define IDM_SELECTED_COPY                       40014
#define IDM_SELECTED_CUT                        40015
#define IDM_SELECTED_PASTE                      40016
#define IDM_SELECTED_DELETE                     40017
#define IDM_LEVEL_COPY                          40018
#define IDM_LEVEL_PASTE                         40019
#define IDM_UP_A_LEVEL                          40020
#define IDM_DOWN_A_LEVEL                        40021
#define IDM_PATHS1                              40022
#define IDM_ABOUT1                              40023
#define IDM_OBJECT_BROWSER                      40024
#define ID_SCROLL_MAP_RIGHT                     40026
#define ID_SCROLL_MAP_DOWN                      40027
#define ID_SHIFT_WINDOW_FOCUS                   40028
#define IDM_LEVEL_1                             40030
#define IDM_LEVEL_2                             40031
#define IDM_LEVEL_3                             40032
#define IDC_COMBO_SORT                          40033
#define IDC_LIST_OBJ                            40035
#define IDM_TOOLBAR_EDIT                        40036
#define IDM_TOOLBAR_ADD                         40037
#define IDM_TOOLBAR_DELETE                      40038
#define ID_SCROLL_MAP_LEFT                      40040
#define ID_SCROLL_MAP_UP                        40041
#define IDM_SELECTION_WRECT                     40042
#define IDM_SELECTION_PRECT                     40043
#define IDM_SELECT_All_TYPES                    40044
#define IDM_SELECT_ITEMS                        40045
#define IDM_SELECT_CRITTERS                     40046
#define IDM_SELECT_SCENERY                      40047
#define IDM_SELECT_WALLS                        40048
#define IDM_SELECT_TILES                        40049
#define IDM_SELECT_MISC                         40050
#define IDC_CHECKBOX1                           40051
#define IDC_CHECKBOX2                           40052
#define IDC_CHECKBOX3                           40053
#define IDC_CHECKBOX4                           40054
#define IDC_CHECKBOX5                           40055
#define IDC_CHECKBOX6                           40056
#define IDC_CHECKBOX7                           40057
#define IDC_CHECKBOX8                           40058
#define IDC_CHECKBOX9                           40059
#define IDC_CHECKBOX10                          40060
#define IDC_CHECKBOX11                          40061
#define IDC_COMBO_L_DIST                        40062
#define IDC_SLIDE_L_INT                         40064
#define IDC_COMBO_SCRIPT                        40065
#define IDC_COMBO_AI_PAC                        40066
#define IDC_EDIT_TEAM_NUM                       40067
#define IDC_BUTTON_INV_ADD                      40068
#define IDC_BUTTON_INV_CLEAR                    40069
#define IDC_LISTVIEW_INV                        40070
#define IDM_EDGES_TOGGLE_VISIBLE                40077
#define IDM_EDGES_CYCLE_SELECTED                40078
#define IDM_EDGES_ADD                           40079
#define IDM_EDGES_DEL                           40080
#define IDM_EDGES_EDIT_LEFT                     40081
#define IDM_EDGES_EDIT_RIGHT                    40082
#define IDM_EDGES_EDIT_TOP                      40083
#define IDM_EDGES_EDIT_BOTTOM                   40084
#define ID_SET_LEVEL                            40085
